name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Version
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Install and Build 🔧
        env:
          REACT_APP_CHAIN_ID: ${{ vars.REACT_APP_CHAIN_ID }}
          REACT_APP_COLLECTION_NAME: ${{ vars.REACT_APP_COLLECTION_NAME }}
          REACT_APP_COLLECTION_IMAGE: ${{ vars.REACT_APP_COLLECTION_IMAGE }}
          REACT_APP_COLLECTION_TOKEN: ${{ vars.REACT_APP_COLLECTION_TOKEN }}
          REACT_APP_CURRENCY_TOKEN: ${{ vars.REACT_APP_CURRENCY_TOKEN }}
          REACT_APP_STORAGE_SERVER_URL: ${{ vars.REACT_APP_STORAGE_SERVER_URL }}
          REACT_APP_WALLET_CONNECT_PROJECT_ID: ${{ vars.REACT_APP_WALLET_CONNECT_PROJECT_ID }}
          REACT_APP_RPC_URL_5: ${{ vars.REACT_APP_RPC_URL_5 }}
        run: |
          yarn
          yarn build

      - name: Pages Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build

      - name: IPFS (Infura)
        uses: aquiladev/ipfs-action@master
        with:
          path: ./build
          service: infura
          infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
          infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}

      - name: IPFS (Pinata)
        uses: aquiladev/ipfs-action@master
        with:
          path: ./build
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}